### ISSUE TITLE
Object detector

### ISSUE THREAD

**Issue by amanchadha** [v-iashin/v-iashin.github.io#5]
Hello Vladimir,

Aman here again. Thanks for answering my previous questions; you close the issues on github before I can even write thanks back :)

Your personal project "object detector" caught my attention. It looks like it is hosted at https://v-iashin.ml:5000, and while its front-end source is on Github the backend isn't accessible, so I am unable to learn what it looks like. Would you mind sharing its source so I can learn a bit about browser-based AI? Is it implemented in TensorFlow.js? Thats been on my to-do list for quite some time :)

Thanks for your support,
Aman

**Comment by v-iashin** [comment]
Hi 🙂 
Thanks for providing your feedback on my projects and asking various questions!

When I was building it, I was learning a lot. Hence, it mostly consists of pieces of ugly engineering. Maybe someone will point out a better way to do all of this. Anyway, the idea boils down to the following things:
1. Front-end on Github (website hosting, js, HTML, CSS, etc.). Packs the image, sends it, waits for a response, shows the results.
2. Since GitHub Pages are good only for static pages, I am renting a small CPU-only preemptible instance on GoogleCloud.
3. The GoogleCloud instance is running a back-end for the object detector. Specifically, the Flask server listens for POST queries and sends back the results. PyTorch with pre-trained YOLO weights does its job in-between. Source code is here: https://github.com/v-iashin/PersonalProjects 
4. The Github pages trust neither naked IPs nor HTTP protocol (it needs HTTPS). Hence, the files cannot be sent using just to 13.45.56.67:5000 or http://v-iashin.ml:5000. So, I am using this domain (v-iashin.ml) and the LetsEncrypt tool to convince Github that the redirection of the user's data is safe.

Thus, it is not TF.js. Recently, I saw a demo on the web using TF.js and YOLO using the webcam stream. I remember that a user has to download the weights first to start running it in the browser. It takes too much time.

Just as a side hint. HerokuApp has a free server with a limited capability, though. You can host your project, as well as front- and back-ends there. YOLO requires more resources than Heroku provides on this free server. So, I decided to do it the other way.

**Comment by v-iashin** [comment]
I will close it for now.

**Comment by v-iashin** [comment]
More details are now organized in a form of a blog post: [How Did You Build Object Detector?](https://v-iashin.github.io/how_did_you_build_my_detector)
